import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { GoalStatus, Prisma, TransactionType } from '@prisma/client';
import { PrismaService } from 'prisma/prisma.service';
import { REALISTIC_TRANSACTION_TEMPLATES } from './data/realistic-transactions.data';
import { SAMPLE_CATEGORY_UPDATES } from './data/sample-categories.data';
import { SAMPLE_SAVINGS_GOALS } from './data/sample-goals.data';
import {
  DevToolActionId,
  DevToolActionResult,
} from './types/dev-tool-action.types';

const TRANSACTIONS_TO_IMPORT = 50;
const TRANSACTIONS_TO_DELETE = 10;
const TRANSACTION_LOOKBACK_DAYS = 90;
const GOAL_TARGET_MONTHS_AHEAD = 6;

type CategoryLookupItem = {
  id: string;
  name: string;
  type: TransactionType;
};

@Injectable()
export class DevToolsService {
  private readonly logger = new Logger(DevToolsService.name);

  constructor(private readonly prisma: PrismaService) {}

  async runAction(
    userId: string,
    actionId: DevToolActionId,
  ): Promise<DevToolActionResult> {
    await this.assertAdminUser(userId);

    const result = await this.executeAction(userId, actionId);

    this.logger.log({
      actionId,
      userId,
      summary: result.summary ?? {},
    });

    return result;
  }

  private executeAction(
    userId: string,
    actionId: DevToolActionId,
  ): Promise<DevToolActionResult> | DevToolActionResult {
    switch (actionId) {
      case 'import-realistic-transactions':
        return this.importRealisticTransactions(userId);
      case 'delete-random-transactions':
        return this.deleteRandomTransactions(userId);
      case 'update-sample-categories':
        return this.updateSampleCategories(userId);
      case 'create-savings-goal':
        return this.createSavingsGoal(userId);
      case 'refresh-analytics':
        return this.refreshAnalytics(actionId);
      default:
        throw new BadRequestException('Unsupported dev tool action.');
    }
  }

  private async assertAdminUser(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { id: true, role: true },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    if (user.role !== 'ADMIN') {
      throw new ForbiddenException('Dev tools are only available for admins.');
    }
  }

  private async importRealisticTransactions(
    userId: string,
  ): Promise<DevToolActionResult> {
    const [account, categories] = await Promise.all([
      this.prisma.account.findFirst({
        where: { userId },
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          name: true,
          currencies: true,
        },
      }),
      this.prisma.category.findMany({
        where: { userId },
        select: {
          id: true,
          name: true,
          type: true,
        },
      }),
    ]);

    if (!account) {
      throw new NotFoundException('Account not found');
    }

    const categoryByName = this.buildCategoryLookup(categories);
    const transactionData: Prisma.TransactionCreateManyInput[] = [];
    let skipped = 0;

    for (let index = 0; index < TRANSACTIONS_TO_IMPORT; index += 1) {
      const template =
        REALISTIC_TRANSACTION_TEMPLATES[
          index % REALISTIC_TRANSACTION_TEMPLATES.length
        ];
      const category = this.findCategoryForTemplate(
        categoryByName,
        template.categoryNames,
        template.type,
      );

      if (!category) {
        skipped += 1;
        continue;
      }

      transactionData.push({
        userId,
        accountId: account.id,
        categoryId: category.id,
        amount: new Prisma.Decimal(
          this.randomAmount(template.amountMin, template.amountMax),
        ),
        currency: this.getPreferredCurrency(account.currencies),
        type: template.type,
        description: template.description,
        notes: 'Generated by dev tools.',
        date: this.getRecentDate(index),
        frequencyType: template.frequencyType,
        transactionNature: template.transactionNature,
      });
    }

    if (transactionData.length === 0) {
      return {
        actionId: 'import-realistic-transactions',
        success: true,
        message: 'No matching categories found for realistic transactions.',
        summary: {
          created: 0,
          skipped,
          account: account.name,
        },
      };
    }

    const result = await this.prisma.transaction.createMany({
      data: transactionData,
    });

    return {
      actionId: 'import-realistic-transactions',
      success: true,
      message: 'Realistic transactions imported.',
      summary: {
        created: result.count,
        skipped,
        account: account.name,
      },
    };
  }

  private async deleteRandomTransactions(
    userId: string,
  ): Promise<DevToolActionResult> {
    const transactions = await this.prisma.transaction.findMany({
      where: { userId },
      select: { id: true },
      orderBy: { createdAt: 'desc' },
      take: 100,
    });

    const selectedIds = this.shuffle(transactions.map(({ id }) => id)).slice(
      0,
      TRANSACTIONS_TO_DELETE,
    );

    if (selectedIds.length === 0) {
      return {
        actionId: 'delete-random-transactions',
        success: true,
        message: 'No transactions available to delete.',
        summary: {
          requested: TRANSACTIONS_TO_DELETE,
          deleted: 0,
        },
      };
    }

    const result = await this.prisma.transaction.deleteMany({
      where: {
        userId,
        id: {
          in: selectedIds,
        },
      },
    });

    return {
      actionId: 'delete-random-transactions',
      success: true,
      message: 'Random transactions deleted.',
      summary: {
        requested: TRANSACTIONS_TO_DELETE,
        deleted: result.count,
      },
    };
  }

  private async updateSampleCategories(
    userId: string,
  ): Promise<DevToolActionResult> {
    const categories = await this.prisma.category.findMany({
      where: { userId },
      select: {
        id: true,
        name: true,
        type: true,
      },
    });

    const categoryByName = this.buildCategoryLookup(categories);
    const updates: ReturnType<typeof this.prisma.category.update>[] = [];

    for (const sample of SAMPLE_CATEGORY_UPDATES) {
      const category = categoryByName.get(
        this.getCategoryLookupKey(sample.matchName, sample.type),
      );

      if (!category) {
        continue;
      }

      updates.push(
        this.prisma.category.update({
          where: { id: category.id },
          data: {
            icon: sample.icon,
            color: sample.color,
          },
        }),
      );
    }

    await this.prisma.$transaction(updates);

    const matched = updates.length;

    return {
      actionId: 'update-sample-categories',
      success: true,
      message: 'Sample category metadata updated.',
      summary: {
        matched,
        updated: matched,
        skipped: SAMPLE_CATEGORY_UPDATES.length - matched,
      },
    };
  }

  private async createSavingsGoal(
    userId: string,
  ): Promise<DevToolActionResult> {
    const sampleGoal = SAMPLE_SAVINGS_GOALS[0];
    const existingGoal = await this.prisma.goal.findFirst({
      where: {
        userId,
        name: sampleGoal.name,
        status: GoalStatus.active,
      },
      select: { id: true },
    });

    if (existingGoal) {
      return {
        actionId: 'create-savings-goal',
        success: true,
        message: 'Savings goal already exists.',
        summary: {
          created: 0,
          skipped: 1,
          reason: 'Goal already exists',
        },
      };
    }

    const targetDate = new Date();
    targetDate.setMonth(targetDate.getMonth() + GOAL_TARGET_MONTHS_AHEAD);

    await this.prisma.goal.create({
      data: {
        userId,
        name: sampleGoal.name,
        description: sampleGoal.description,
        targetAmount: new Prisma.Decimal(sampleGoal.targetAmount),
        currentAmount: new Prisma.Decimal(sampleGoal.currentAmount),
        currency: sampleGoal.currency,
        targetDate,
        type: sampleGoal.type,
        icon: sampleGoal.icon,
        color: sampleGoal.color,
      },
    });

    return {
      actionId: 'create-savings-goal',
      success: true,
      message: 'Savings goal created.',
      summary: {
        created: 1,
        name: sampleGoal.name,
      },
    };
  }

  private refreshAnalytics(actionId: DevToolActionId): DevToolActionResult {
    return {
      actionId,
      success: true,
      message: 'Analytics refreshed.',
      summary: {
        refreshed: true,
        mode: 'computed-live',
      },
    };
  }

  private buildCategoryLookup(categories: CategoryLookupItem[]) {
    return new Map(
      categories.map((category) => [
        this.getCategoryLookupKey(category.name, category.type),
        category,
      ]),
    );
  }

  private findCategoryForTemplate(
    categoryByName: Map<string, CategoryLookupItem>,
    categoryNames: string[],
    type: TransactionType,
  ) {
    for (const categoryName of categoryNames) {
      const category = categoryByName.get(
        this.getCategoryLookupKey(categoryName, type),
      );

      if (category) {
        return category;
      }
    }

    return null;
  }

  private getCategoryLookupKey(name: string, type: TransactionType) {
    return `${type}:${name.trim().toLowerCase()}`;
  }

  private getPreferredCurrency(currencies: string[]) {
    return currencies[0]?.trim().toUpperCase() || 'EUR';
  }

  private randomAmount(min: number, max: number) {
    const value = min + Math.random() * (max - min);

    return value.toFixed(2);
  }

  private getRecentDate(index: number) {
    const date = new Date();
    const daysAgo = (index * 7) % TRANSACTION_LOOKBACK_DAYS;

    date.setDate(date.getDate() - daysAgo);
    date.setHours(10 + (index % 10), 0, 0, 0);

    return date;
  }

  private shuffle<T>(items: T[]) {
    const nextItems = [...items];

    for (let index = nextItems.length - 1; index > 0; index -= 1) {
      const swapIndex = Math.floor(Math.random() * (index + 1));
      [nextItems[index], nextItems[swapIndex]] = [
        nextItems[swapIndex],
        nextItems[index],
      ];
    }

    return nextItems;
  }
}
