name: Build, Push & Deploy Welmio

on:
  push:
    branches:
      - pre
      - prod

jobs:
  build-and-push:
    if: github.ref_name == 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API image
        run: |
          docker build \
            -f apps/api/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/welmio-api:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/welmio-api:prod \
            .

      - name: Push API image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/welmio-api:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/welmio-api:prod

      - name: Build APP image
        run: |
          docker build \
            -f apps/app/Dockerfile \
            --build-arg EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/welmio-app:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/welmio-app:prod \
            .

      - name: Push APP image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/welmio-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/welmio-app:prod

      - name: Build WEB image
        run: |
          docker build \
            -f apps/web/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/welmio:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/welmio:prod \
            .

      - name: Push WEB image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/welmio:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/welmio:prod

  deploy:
    if: github.ref_name == 'prod'
    needs: build-and-push
    runs-on: [self-hosted, welmio, prod]

    steps:
      - name: Deploy on server
        run: |
          cd /opt/welmio
          docker compose pull
          docker compose up -d