name: Build, Push & Deploy Welmio

on:
  push:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (welmio)
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_REPO }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_REPO }}:latest

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, welmio, prod]

    steps:
      - name: Deploy on server
        run: |
          cd /opt/welmio
          docker compose pull
          docker compose up -d
